<?php if (isset($this->_data['filter'])) {
    $filter = $this->_data['filter'];
} else {
    $filter = null;
}
?>

<form method='get'>
    <select name="filter">
        <option value="All status">All status</option>
        <option value="TO DO" <?php echo ($filter == 'TO DO') ? 'selected' : ''; ?>>TO DO</option>
        <option value="DOING" <?php echo ($filter == 'DOING') ? 'selected' : ''; ?>>DOING</option>
        <option value="DONE" <?php echo ($filter == 'DONE') ? 'selected' : ''; ?>>DONE</option>
    </select>
    <input type="submit" value="Search">
</form>