<?php
echo "This is the home screen";
?>
<br>
<div>
    <?php
    $data = array();
    $data = $this->_data['_data'];
    $i = 0;
    while ($i < count($data)) {
        ?>
        <br>
        <p>
            <?php print($data[$i]->status) ?>
        </p>
        <h2>
            <?php print($data[$i]->title) ?>
        </h2>
        <p>
            <?php print($data[$i]->desc) ?>
        </p>
        <?php
        $i++;
    }
    ?>
</div>


<br>
<button type="button" onclick="window.location='./task'">Single Task</button>