<?php
$data = array();
$data = $this->_data['data'];
$i = 0;
while ($i < count($data)) {
    ?>
    <div class="p-4 pt-3 bg-white rounded-lg items-center justify-between">
        <div>
            <?php if ($data[$i]->status == "TO DO") { ?>
                <span
                    class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300">
                    <?php print($data[$i]->status) ?>
                </span>
            <?php } else {
                if ($data[$i]->status == "DOING") { ?>
                    <span
                        class="bg-yellow-100 text-yellow-800 text-xs font-semibold mr-2 px-2.5 py-0.5 rounded dark:bg-yellow-900 dark:text-yellow-300">
                        <?php print($data[$i]->status) ?>
                    </span>

                <?php } else { ?>
                    <span
                        class="bg-green-100 text-green-800 text-xs font-semibold mr-2 px-2.5 py-0.5 rounded dark:bg-green-900 dark:text-green-300">
                        <?php print($data[$i]->status) ?>
                    </span>
                <?php }
            } ?>
        </div>
        <div class="flex items-center mt-2 space-x-3">
            <div class="h-5 flex w-10/12 text-sm space-x-3 overflow-hidden">
                <div class="h-5 font-bold flex-none">
                    <?php print($data[$i]->title) ?>
                </div>
                <div class="h-5 text-gray-400"><?php print($data[$i]->desc) ?></div>
            </div>
            <?php $taskId = $data[$i]->taskId ?>
            <div class="text-sm text-right font-medium text-blue-400 leading-none">
                <?php echo "<a class='flex' href='update_task?taskId=" . $taskId . "'><i class='fa-solid fa-pen-to-square'></i>&nbspEdit</a>" ?>
            </div>
            <div onclick="confirmDelete()" class="text-sm items-center text-right text-red-400 font-medium leading-none">
                <?php echo "<a class='flex' href='delete?taskId=" . $taskId . "'><i class='fa-solid fa-trash'></i>&nbspDelete</a>" ?>
            </div>
        </div>
    </div>
    <?php
    $i++;
}
?>
<script>
function confirmDelete() {
  confirm("Are you sure you want to delete this task?");
}
</script>