<?php
$data = array();
$data = $this->_data['data'];
$i = 0;
while ($i < count($data)) {
?>
    <div class="p-4 pt-3 bg-white rounded-lg items-center justify-between">
        <div>
            <?php if ($data[$i]->status == "TO DO") { ?>
                <span class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300">
                    <?php print($data[$i]->status) ?>
                </span>
                <?php } else {
                if ($data[$i]->status == "DOING") { ?>
                    <span class="bg-yellow-100 text-yellow-800 text-xs font-semibold mr-2 px-2.5 py-0.5 rounded dark:bg-yellow-900 dark:text-yellow-300">
                        <?php print($data[$i]->status) ?>
                    </span>

                <?php } else { ?>
                    <span class="bg-green-100 text-green-800 text-xs font-semibold mr-2 px-2.5 py-0.5 rounded dark:bg-green-900 dark:text-green-300">
                        <?php print($data[$i]->status) ?>
                    </span>
            <?php }
            } ?>
        </div>
        <div class="flex justify-between items-center h-4 mt-2 space-x-3">
            <div class="flex w-10/12 text-sm space-x-3">
                <div class="font-bold">
                    <?php print($data[$i]->title) ?>
                </div>
                <div class="text-gray-400"><?php print($data[$i]->desc) ?></div>
            </div>
            <div class="w-1/12 text-sm"><?php $taskId = $data[$i]->taskId;
                        echo "<a href='update_task?taskId=" . $taskId . "'>Edit</a>"?>
            </div>
            <div class="w-1/12 text-sm">
                <form action="./delete" method="post">
                    <input type="hidden" name="taskId" value="<?= $data[$i]->taskId ?>">
                    <button class="btn" style="border: 2px solid red; border-radius: 5px; padding: 2px; background-color: white; color: red;">Delete</button>
                </form>
            </div>
        </div>
    </div>
<?php
    $i++;
}
?>