<form action="" method='get' class="flex justify-between space-x-3">
    <div class="my-2 w-2/3">
        <?php include 'search.phtml' ?>
    </div>
    <div class="w-1/3 flex justify-between space-x-3 ml-2 my-2">
        <?php include 'filter.phtml' ?>
        <button type="submit"
            class="justify-center align-center text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-2.5 py-2.5 text-center flex justify-between space-x-1">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                    </svg>
            <span>Search</span>
        </button>
    </div>

</form>