TASK EDITOR
<br><br>
<form method="post">
    Title: <input type="text" name="title"><br><br>
    Description: <input type="text" name="desc"><br><br>
    Status: <select name="status">
        <option value="todo">To Do</option>
        <option value="doing">Doing</option>
        <option value="done">Done</option>
    </select><br><br>
    <input type="submit">
</form>

<?php


if (isset($_POST["title"]) && isset($_POST["desc"]) && isset($_POST["status"])) {
    
    $model = new Tasks;
    
    $id = $model->getLastTaskID();
    //"task_id" to set index in DB, ++task_id to set new "task_id" value
    $newData = array(
        $id => array(
        "user_id" => 1,
        "email" => "myemail@email.com",
        "pwd" => "1234",
        "name" => "UserName",
        "task_id" => ++$id,
        "title" => $_POST["title"],
        "desc" => $_POST["desc"],
        "status" => $_POST["status"],
        "start_date" => $model->setDate(),
        "mod_date" => "",
        "end_date" => ""
    ));

    $model->addTask($newData);
    echo "<br>"."Saved Data"."<br>";

    //TESTING
    $table = $model->getData();
    echo "<pre>";
    var_dump($table);
    echo "</pre>";

}

?>