TASK EDITOR
<br><br>
<form method="post">
    Title: <input type="text" name="title"><br><br>
    Description: <input type="text" name="desc"><br><br>
    Status: <select name="status">
        <option value="todo">To Do</option>
        <option value="doing">Doing</option>
        <option value="done">Done</option>
    </select><br><br>
    <input type="submit">
</form>

<?php


if (isset($_POST["title"]) && isset($_POST["desc"]) && isset($_POST["status"])) {
    
    $model = new Tasks;
    $dbData = $model->getData();
    $lastItem = end($dbData);
    $lastItemId = $lastItem->{"task_id"};

    $newData = array(
        $lastItemId => array(
        "user_id" => 1,
        "name" => "UserName",
        "task_id" => ++$lastItemId,
        "title" => $_POST["title"],
        "desc" => $_POST["desc"],
        "status" => $_POST["status"],
        "start_date" => $model->setDate(),
        "mod_date" => "",
        "end_date" => ""
    ));

    $mergedData = array_merge($dbData, $newData);
    $encodedMerge = json_encode($mergedData, JSON_PRETTY_PRINT);
    $model->saveData($encodedMerge);
    echo "Saved Data";
    $table = $model->getData();
    echo "<pre>";
    var_dump($table);
    echo "</pre>";

}

?>