<?php 

if (!empty($task)) {
    if (!empty($task->endDate)){
        $date = "Ended at date: ".$task->endDate;
    } else if(!empty($task->modDate)){
        $date = "Modified at date: ".$task->modDate;
    } else if(!empty($task->startDate)){
        $date = "Created at date: ".$task->startDate;
    }
} else{
    $date="";
}
?>

<div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">

    <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
        <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
            <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                Task fields
            </h1>
            <form class="space-y-4 md:space-y-6" method="post" action="<?= $action?>" id="taskform">
                <div>
                    <label for="title" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Title</label>
                    <input value="<?php if (!empty($task)) {
                                        echo $task->title;
                                    } ?>" type="text" name="title" id="title" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Title..." required="">
                </div>
                <div>
                    <label for="desc" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
                    <textarea placeholder="Description..." form="taskform" name="desc" id="desc" cols="30" rows="10" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required=""><?php if (!empty($task)) {echo $task->desc;} ?></textarea>
                </div>
                <div>
                    <label for="status" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Status</label>
                    <select name="status" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
                        <option value="TO DO" <?php if (!empty($task)) {
                                                    echo ($task->status == 'TO DO') ? 'selected' : '';
                                                } ?>>TO DO</option>
                        <option value="DOING" <?php if (!empty($task)) {
                                                    echo ($task->status == 'DOING') ? 'selected' : '';
                                                } ?>>DOING</option>
                        <option value="DONE" <?php if (!empty($task)) {
                                                    echo ($task->status == 'DONE') ? 'selected' : '';
                                                } ?>>DONE</option>
                    </select>
                </div>
                <div>
                    <p class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                        <?= (!empty($task)) ? $date : ""; ?>
                    </p>
                </div>
                <button type="submit" class="w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                    <?= $button ?>
                </button>

            </form>
            <button type="submit" class="w-full text-white bg-red-600 hover:bg-red-700 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800">
                <a href="./home">Cancel</a>
            </button>
        </div>
    </div>
</div>