<!-- HOME LAYOUT-->

<!-- HTML HEAD-->
<?php include "partials/htmlHead.php"?>

<!-- NAV BAR-->
<body class="h-full">

  <div class="min-h-full">
    <nav class="bg-gray-800">
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div class="flex h-16 items-center justify-between">
          <div class="flex items-center">
            <div class="flex-shrink-0">
              <img class="h-8 w-8" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/logo.svg" alt="Your Company">
            </div>
            <div class="hidden md:block">

              <div class="ml-10 flex items-baseline space-x-4">
                <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                <a href="./home" class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium" aria-current="page">Home</a>

                <a href="./task" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">New Task</a>

              </div>
            </div>
          </div>
          <div class="hidden md:block">
            <div class="ml-4 flex items-center md:ml-6">
              
              <button type="button" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
                <span class="sr-only">Sign out</span>
                <a href="./">Sign out</a>
              </button>
              <div class="relative ml-3">
                <div>
                  <img class="h-8 w-8 rounded-full" src="./images/user.jpg" alt="Avatar">
                </div>
              </div>
            </div>
          </div>

    <!-- RESPONSIVE MOBILE -->
    <?php include "partials/mobile.php"?>
    <!-- HEADER -->
    <?php include "partials/header.php"?>
    <main>
      <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
        <?php echo $this->content(); ?>
      </div>
    </main>
  </div>

</body>

</html>